name: "Main"
on:
  push:

jobs:
  build-test:
    runs-on: ubuntu-16.04
    name: Build test
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Do an arm64 build
        run: |
          docker version
          docker run --rm --privileged docker/binfmt:820fdd95a9972a5308930a2bdfb8573dd4447ad3
          cat /proc/sys/fs/binfmt_misc/qemu-aarch64
          docker buildx create --name dappnode-arm-builder
          docker buildx use dappnode-arm-builder
          docker buildx inspect --bootstrap
          docker buildx build --progress plain --platform linux/arm64 -t dappmanager.dnp.dappnode.eth:arm64-test --load .
        env:
          DOCKER_CLI_EXPERIMENTAL: enabled
