name: "Main"
on:
  pull_request:
  push:
    branches:
      - "master"
      - "v[0-9]+.[0-9]+.[0-9]+"
    paths-ignore:
      - "README.md"

jobs:
  unit-test:
    runs-on: ubuntu-latest
    name: Unit tests
    steps:
      - uses: actions/checkout@v2
      - name: Setup node
        uses: actions/setup-node@v1
        with:
          node-version: "12.22.0"
      - run: yarn
      - run: yarn bootstrap
      - run: yarn generate
      - run: yarn test
      - run: yarn server-mock:check-types
        working-directory: packages/admin-ui

  integration-test:
    runs-on: ubuntu-latest
    name: In app integration tests
    steps:
      - uses: actions/checkout@v2
      - name: Setup node
        uses: actions/setup-node@v1
        with:
          node-version: "12.22.0"
      - run: yarn # Caching only saves 30s
      - run: yarn bootstrap
      - run: yarn generate
      - run: yarn test:int

  release:
    name: Release
    runs-on: ubuntu-latest
    needs: [unit-test, integration-test]
    if: github.event_name == 'push'
    steps:
      - uses: actions/checkout@v2
      - name: Setup node
        uses: actions/setup-node@v1
        with:
          node-version: "12.22.0"
      - name: Publish
        run: npx @dappnode/dappnodesdk publish patch --dappnode_team_preset
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
